//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioView.Common.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public System.Guid Id { get; set; }
        public System.Guid Project { get; set; }
        public System.DateTime Time { get; set; }
        public byte Major { get; set; }
        public double LAeq { get; set; }
    
        public virtual Project Project1 { get; set; }
    }
}
