//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioView.Common.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public System.Guid Id { get; set; }
        public System.Guid Project { get; set; }
        public System.DateTime Time { get; set; }
        public byte Major { get; set; }
        public double LAeq { get; set; }
        public double LAMax { get; set; }
        public double LAMin { get; set; }
        public double LZMax { get; set; }
        public double LZMin { get; set; }
        public double Hz6_3 { get; set; }
        public double Hz8 { get; set; }
        public double Hz10 { get; set; }
        public double Hz12_5 { get; set; }
        public double Hz16 { get; set; }
        public double Hz20 { get; set; }
        public double Hz25 { get; set; }
        public double Hz31_5 { get; set; }
        public double Hz40 { get; set; }
        public double Hz50 { get; set; }
        public double Hz63 { get; set; }
        public double Hz80 { get; set; }
        public double Hz100 { get; set; }
        public double Hz125 { get; set; }
        public double Hz160 { get; set; }
        public double Hz200 { get; set; }
        public double Hz250 { get; set; }
        public double Hz315 { get; set; }
        public double Hz400 { get; set; }
        public double Hz500 { get; set; }
        public double Hz630 { get; set; }
        public double Hz800 { get; set; }
        public double Hz1000 { get; set; }
        public double Hz1250 { get; set; }
        public double Hz1600 { get; set; }
        public double Hz2000 { get; set; }
        public double Hz2500 { get; set; }
        public double Hz3150 { get; set; }
        public double Hz4000 { get; set; }
        public double Hz5000 { get; set; }
        public double Hz6300 { get; set; }
        public double Hz8000 { get; set; }
        public double Hz10000 { get; set; }
        public double Hz12500 { get; set; }
        public double Hz16000 { get; set; }
        public double Hz20000 { get; set; }
        public double OOHz31_5 { get; set; }
        public double OOHz63 { get; set; }
        public double OOHz125 { get; set; }
        public double OOHz250 { get; set; }
        public double OOHz500 { get; set; }
        public double OOHz1000 { get; set; }
        public double OOHz2000 { get; set; }
        public double OOHz4000 { get; set; }
        public double OOHz8000 { get; set; }
        public double OOHz16000 { get; set; }
        public double OOHz16 { get; set; }
    
        public virtual Project Project1 { get; set; }
    }
}
